import json
import os
import sys

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

# Model specified for this tool: GroqCloud llama-3.1-8b-instant
MODEL = "llama-3.1-8b-instant"

# A stronger model judges diagnose() output. Self-grading with the small generator
# model tends to be lenient, so the eval uses a more capable model for sharper,
# more discriminating scores. Override via the EVAL_MODEL env var.
EVAL_MODEL = os.environ.get("EVAL_MODEL", "llama-3.3-70b-versatile")


def _client() -> Groq:
    """Build a Groq client from the GROQ_API_KEY in the environment."""
    return Groq(api_key=os.environ["GROQ_API_KEY"])

SYSTEM_PROMPT = """You are an automation diagnosis coach for data analysts who are \
new to automation. Given a description of an analyst's day-to-day workflow, your job \
is to diagnose where automation will help most and produce a concrete plan they can \
follow to build their FIRST automation.

Pick the single best first automation using these rules:
- High frequency (happens often) beats rare one-offs.
- Low complexity and low risk beats a big ambitious project.
- Clear, repetitive, rules-based steps beat fuzzy judgement work.
The goal is a quick win that builds confidence.

Respond in Markdown with EXACTLY these sections, in order:

## Workflow Summary
Restate what the analyst does, in 2-3 sentences.

## Automation Opportunities
A ranked list of the manual/repetitive steps that could be automated. For each,
note (frequency, complexity) in parentheses.

## Best First Automation
Name the single highest-ROI automation to build first.

## Why This One
2-4 sentences: time saved, low risk, why it's a good starting point.

## Step-by-Step Build Plan
Numbered, concrete steps to build it. Be specific and beginner-friendly.

## Suggested Tools / Stack
Practical tools the analyst could use (spreadsheets, Python, no-code, APIs, etc.).
"""


def diagnose(workflow_description: str) -> str:
    """Diagnose an analyst's workflow and return a first-automation build plan.

    Args:
        workflow_description: Plain-English description of the analyst's workflow.

    Returns:
        A Markdown diagnosis plan generated by the LLM.
    """
    response = _client().chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": workflow_description},
        ],
        temperature=0.4,
    )
    return response.choices[0].message.content


EVAL_CRITERIA = [
    "Workflow Fidelity",
    "Opportunity Coverage",
    "Ranking Quality",
    "Best-Pick Correctness",
    "ROI Justification",
    "Actionability",
    "Beginner-Appropriateness",
    "Tool Fit",
    "Risk Awareness",
    "Specificity",
    "Scope Discipline",
    "Measurability",
    "Structure & Completeness",
    "Clarity & Simplicity",
    "Next-Step Momentum",
]

EVAL_SYSTEM_PROMPT = """You are an automation strategy evaluator trained in lean, \
high-ROI automation principles for non-technical analysts.

You will receive (1) an analyst's original workflow description and (2) a diagnosis \
plan produced for that workflow. Judge the PLAN, not the workflow. A great plan is \
accurate to the stated workflow, picks the genuinely highest-ROI first automation, \
and gives a beginner enough to actually build it. Penalize invented facts, vague \
steps, and over-ambitious first projects.

Score the plan out of 100 using these 15 principles, each worth up to 6.7 points:
1. Workflow Fidelity — accurately reflects the actual workflow; nothing invented or dropped.
2. Opportunity Coverage — the real automatable steps are identified; none obvious missed.
3. Ranking Quality — opportunities ranked sensibly by frequency and complexity.
4. Best-Pick Correctness — the chosen first automation is the highest-ROI, lowest-risk quick win.
5. ROI Justification — "why this one" is backed by concrete reasoning, not hand-waving.
6. Actionability — build steps are concrete and ordered enough to start today.
7. Beginner-Appropriateness — difficulty is realistic for a non-technical first automation.
8. Tool Fit — suggested tools are practical, accessible, and not over-engineered.
9. Risk Awareness — flags where things break (bad data, auth, edge cases) or how to validate.
10. Specificity — steps and tools are specific, not generic filler.
11. Scope Discipline — first automation stays small and shippable.
12. Measurability — the win is measurable (time saved, errors reduced).
13. Structure & Completeness — all six required sections present, in order, well-formatted.
14. Clarity & Simplicity — plainspoken, jargon-light, easy to follow.
15. Next-Step Momentum — leaves an obvious first move and a path to the next automation.

Return ONLY a JSON object with this exact shape (no markdown, no commentary):
{
  "overall_score": <number 0-100>,
  "breakdown": [
    {"principle": "Workflow Fidelity", "score": <0-6.7>, "comment": "<short>"},
    ... one entry per principle, in the order listed above ...
  ],
  "top_3_improvements": ["<area 1>", "<area 2>", "<area 3>"],
  "suggested_edits": ["<edit>", "..."],
  "rewrite": "<full rewritten diagnosis plan keeping the six-section format>"
}
"""


def evaluate(workflow_description: str, plan: str) -> dict:
    """Evaluate a diagnosis plan against its source workflow (LLM-as-judge).

    Args:
        workflow_description: The input originally passed to diagnose().
        plan: The diagnosis plan returned by diagnose().

    Returns:
        A dict with keys: overall_score, breakdown, top_3_improvements,
        suggested_edits, rewrite. If the model returns unparseable JSON, the
        raw text is returned under {"raw": ...}.
    """
    user_content = (
        f"**Original Workflow Description:**\n{workflow_description}\n\n"
        f"**Diagnosis Plan to Evaluate:**\n{plan}"
    )

    response = _client().chat.completions.create(
        model=EVAL_MODEL,
        messages=[
            {"role": "system", "content": EVAL_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        return {"raw": content}


SAMPLE_WORKFLOW = (
    "Every morning I download 3 CSV sales reports from our dashboard, "
    "open them in Excel, clean up the columns, combine them into one sheet, "
    "calculate daily totals per region, and paste a summary into an email "
    "that I send to my manager. It takes about an hour each day."
)


def _read_workflow_from_cli() -> str:
    """Get the workflow description from CLI args or interactive prompt.

    Priority:
    1. Command-line arguments joined into one string (e.g. `python main.py "I do X..."`).
    2. Piped stdin (e.g. `cat workflow.txt | python main.py`).
    3. Interactive prompt.
    Falls back to SAMPLE_WORKFLOW if nothing is provided.
    """
    args = [a for a in sys.argv[1:] if a != "--eval"]
    if args:
        return " ".join(args)

    if not sys.stdin.isatty():
        piped = sys.stdin.read().strip()
        if piped:
            return piped

    try:
        entered = input(
            "Describe the analyst's workflow (or press Enter for the sample):\n> "
        ).strip()
    except EOFError:
        entered = ""
    return entered or SAMPLE_WORKFLOW


if __name__ == "__main__":
    workflow = _read_workflow_from_cli()
    plan = diagnose(workflow)
    print(plan)

    if "--eval" in sys.argv:
        print("\n" + "=" * 60)
        print("EVALUATION")
        print("=" * 60)
        result = evaluate(workflow, plan)
        if "raw" in result:
            print(result["raw"])
        else:
            print(f"\nOverall Score: {result['overall_score']}/100\n")
            for row in result.get("breakdown", []):
                print(f"  {row['score']:>4}  {row['principle']}: {row['comment']}")
            print("\nTop 3 Improvements:")
            for i, area in enumerate(result.get("top_3_improvements", []), 1):
                print(f"  {i}. {area}")
